version: '3'

services: 
    store-postgres:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: "admin"
        ports: 
            - "15432:15432"
        volumes: 
            - .:/usr/postgres
        networks: 
            - postgres-network
    store-pgadmin:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: "rodrigo.conte14@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports: 
            - "16543:80"
        depends_on: 
            - store-postgres
        networks: 
            - postgres-network

networks: 
    postgres-network:
        driver: bridge